name: clever_commandbar
description: A flutter plugin to show a Ctrl + K style command bar.
version: 0.7.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  clever_logger: ^1.0.1+1
  fuzzywuzzy: ^0.2.0
  scrollable_positioned_list: ^0.3.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
